# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.Subject'),
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
