# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20171102_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thread',
            new_name='subject',
        ),
    ]
