# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20171103_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='user',
            new_name='user_id',
        ),
    ]
