# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_threadlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='likes',
        ),
    ]
