# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20171107_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadlikes',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='threadlikes',
            name='user',
        ),
        migrations.DeleteModel(
            name='ThreadLikes',
        ),
    ]
