# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_subject_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
