# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171031_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdetails',
            name='staff_key',
        ),
        migrations.DeleteModel(
            name='StaffDetails',
        ),
    ]
