# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='WO_images')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
