# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_whatson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatson',
            name='image',
        ),
    ]
