# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20171202_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
