# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonialpost',
            old_name='author_key',
            new_name='user',
        ),
    ]
