# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_remove_testimonialpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialpost',
            name='title',
            field=models.CharField(default='safasf', max_length=200),
            preserve_default=False,
        ),
    ]
