# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_testimonialpost_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonialpost',
            old_name='author_key',
            new_name='user_id',
        ),
    ]
