# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0004_auto_20171103_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonialpost',
            old_name='user_id',
            new_name='user',
        ),
    ]
